const { MessageStation } = require("@cosmos/utils");
const shortid = require('shortid');
const puppeteer = require('puppeteer');
const xml2js = require('xml2js');
const fs = require('fs').promises;
const axios = require('axios');
const cheerio = require('cheerio');

const ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9';
const result = { collections: ['all'], items: { 'all': [] } };

const extraction = async (context) => {
    const { client, entry, base, ...rest } = context;
    const result = { ...rest, url: entry, spec: [], related: [], };
    result.strategy = "guess";
    result.source = "official";
    result.lang = "en";
    result.brand = "Guess";
    result.brandID = 250;
    try {
        const browser = await puppeteer.launch({ headless: false, args: ['--no-sandbox',], });
        const page = (await browser.pages())[0];
        await page.setExtraHTTPHeaders({ 'user-agent': ua, });
        await page.goto(entry, { waitUntil: ['load', 'domcontentloaded', 'networkidle0', 'networkidle2'], timeout: 0 });
        const data = await page.evaluate(() => document.body.innerHTML);
        const $ = cheerio.load(data);
        result.name = $('.product-detail__name').text();
        if (result.name) {
            result.retail = $('.product-detail__prices').text().replace(/\s+/g, "").trim();
            result.description = $("#description-1").text().replace(/\s+/g, " ").trim();
            result.gender = entry.match(/women/i) ? 'F' : 'M';
            result.thumbnail = $('.product-detail__image').find('img').attr('src');
            $('#details-1').find('li').each((idx, el) => {
                result.spec.push($(el).text().trim())
            })
            $('#details-1').find('div').each((idx, el) => {
                result.spec.push($(el).text().trim())
            })
            const ref = $('.mt-3').last().text().trim();
            result.reference = ref.split("#")[1].trim();
            // result.spec.push(ref);
        } else {
            result.code = 404;
        }
        await browser.close();
    } catch (error) {
        console.error('Failed extraction for Guess with error : ' + error);
        console.error('entry :', entry);
        if (error.response) result.code = error.response.status;
        else result.code = 'UNKNOWN ERROR';
    }
    return result;
};

const indexing = async () => {
    const e = "https://www.guess.com/us/sitemap_0-product.xml";
    const source = "official";
    const lang = "en";
    const brand = "Guess";
    const brandID = 250;
    const result = { source, lang, brand, brandID, collections: ['all'], items: { 'all': [] } };
    // const browser = await puppeteer.launch({
    //     headless: false,
    //     // executablePath: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome",
    //     args: ['--no-sandbox',],
    // });
    // const page = await browser.newPage();
    // await page.setExtraHTTPHeaders({
    //     'user-agent': ua,
    // })
    // await page.goto(e, { waitUntil: ['load', 'domcontentloaded', 'networkidle0', 'networkidle2'], timeout: 0 });
    // const data = await page.evaluate(() => document.body.innerHTML);
    const data = await fs.readFile("./guess.xml");
    const $ = cheerio.load(data);
    $("url").each((idx, el) => {
        const url = $(el).find("loc").text();
        if (url.match(/watch/i)) {
            const thumbnail = $(el).find("image\\:loc").first().text();
            const name = $(el).find("image\\:title").first().text();
            const ref = url.replace(".html", "").split("/");
            const reference = ref[ref.length - 1];
            result.items['all'].push({
                source, lang, brand, brandID, reference, name, url, thumbnail, retail: null,
            });
        }
    })
    console.log("indexing done.....");
}

(async () => {
    const station = await MessageStation.connect({
        // production
        // host: "mq.ieplsg.com",
        // user: "synopsis",
        // pass: "2rbrwWwwEErLwRCMrJUZ",
        // vhost: "/cs",
        // local
        host: "127.0.0.1",
        user: "synopsis",
        pass: "synopsis",
        vhost: "/lc",
    });
    const channel = await station.createChannel();
    // indexing
    // const idx = await indexing();
    // if (result.items['all'].length > 0) {
    //     await channel.publish(
    //         'scraper',
    //         'collector',
    //         Buffer.from(JSON.stringify(idx)),
    //         { correlationId: shortid.generate() });
    // }
    // extraction
    const urls = [
        "https://www.guess.com/us/en/44mm-red-perforated-guess-connect-smartwatch-touch-strap-red/CS1002S10-NC.html",
        "https://www.guess.com/us/en/black-analog-watch-black/U1072G3-NC.html",
        "https://www.guess.com/us/en/black-and-gold-tone-chronograph-watch-gold/U1070L5-GOLD.html",
        "https://www.guess.com/us/en/black-and-gold-tone-oversized-watch-black/U0972G2-NC.html",
        "https://www.guess.com/us/en/black-and-red-silicone-multifunction-watch-red/GW0268G2-MULTI.html",
        "https://www.guess.com/us/en/black-compass-analog-watch-multiplecolors/GW0327G2-MULTI.html",
        "https://www.guess.com/us/en/black-leather-strap-analog-watch-multiplecolors/GW0251G2-MULTI.html",
        "https://www.guess.com/us/en/black-logo-digital-watch-black/C3002M2-BLK.html",
        "https://www.guess.com/us/en/black-metal-barrel-analog-watch-black/GW0387G3-MULTI.html",
        "https://www.guess.com/us/en/blue-analog-watch-blue/U1214G4-LTBL.html",
        "https://www.guess.com/us/en/blue-and-rose-gold-tone-silicone-watch-multiplecolors/GW0051G3-MULTI.html",
        "https://www.guess.com/us/en/blue-diamond-rectangular-watch-blue/U1074G2-NC.html",
        "https://www.guess.com/us/en/brown-and-rose-gold-tone-leather-sport-watch-brown/U0673G3-NC.html",
        "https://www.guess.com/us/en/collections/all-collections/guess-originals/guess-originals-black-analog-watch-black/V1041M2-BLK.html",
        "https://www.guess.com/us/en/collections/all-collections/guess-pride/kaleidoscope-tie-dye-rhinestone-analog-watch-multiplecolors/GW0251L1-MULTI.html",
        "https://www.guess.com/us/en/collections/all-collections/guess-pride/tie-dye-crystal-analog-watch-multiplecolors/GW0250L1-MULTI.html",
        "https://www.guess.com/us/en/collections/all-collections/jennifer-lopez/iridescent-crystal-multifunction-watch-metallic/GW0044L1-PURPL.html",
        "https://www.guess.com/us/en/collections/all-collections/jennifer-lopez/rose-gold-tone-and-black-multifunction-watch-blue/GW0030L5-BLUE.html",
        "https://www.guess.com/us/en/collections/all-collections/jennifer-lopez/rose-gold-tone-multifunction-watch-pink/U1156L3-ROGD.html",
        "https://www.guess.com/us/en/collections/all-collections/jennifer-lopez/silver-tone-square-analog-watch-silver/GW0026L1-SLV.html",
        "https://www.guess.com/us/en/diamond-sport-black-analog-watch-black/U1194G4-BLK.html",
        "https://www.guess.com/us/en/gc-gold-tone-and-black-grid-chronograph-watch-gold/Y70004G2MF-GLD.html",
        "https://www.guess.com/us/en/gold-tone-analog-diamond-watch-gold/U1194G3-GOLD.html",
        "https://www.guess.com/us/en/gold-tone-and-black-chrono-multifunction-watch-gold/U1295L2-GOLD.html",
        "https://www.guess.com/us/en/gold-tone-and-black-leather-strap-analog-watch-multiplecolors/GW0251G1-MULTI.html",
        "https://www.guess.com/us/en/gold-tone-and-black-tachymeter-watch-multiplecolors/GW0204G1-MULTI.html",
        "https://www.guess.com/us/en/gold-tone-chronograph-watch-gold/U0668G8-NC.html",
        "https://www.guess.com/us/en/gold-tone-classic-multifunction-watch-gold/U0791G2-NC.html",
        "https://www.guess.com/us/en/gold-tone-diamond-mesh-watch-gold/U1197L5-GOLD.html",
        "https://www.guess.com/us/en/gold-tone-logo-analog-watch-gold/U1142L2-GOLD.html",
        "https://www.guess.com/us/en/gold-tone-mesh-analog-watch-gold/U1263G2-GOLD.html",
        "https://www.guess.com/us/en/gold-tone-slim-mesh-diamond-watch-gold/U0280G3-NC.html",
        "https://www.guess.com/us/en/guess-originals-grey-analog-watch-gray/V1041M3-GRAY.html",
        "https://www.guess.com/us/en/guess-originals-teal-analog-watch-blue/V1040M5-TURQ.html",
        "https://www.guess.com/us/en/gunmetal-tone-modern-chronograph-watch-gray/U0668G2-NC.html",
        "https://www.guess.com/us/en/iridescent-crystal-multifunction-watch-metallic/GW0044L1-PURPL.html",
        "https://www.guess.com/us/en/kaleidoscope-tie-dye-rhinestone-analog-watch-multiplecolors/GW0251L1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/sale/44mm-orange-textured-silicone-guess-connect-smartwatch-strap-orange/CS1002S16-ORANG.html",
        "https://www.guess.com/us/en/men/accessories/sale/black-and-gold-tone-multifunction-watch-black/GW0205G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/sale/black-and-silver-tone-analog-watch-silver/GW0277G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/sale/black-multifunction-watch-multiplecolors/Y35006G2-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/sale/gold-and-silver-tone-chrono-look-multifunction-watch-silver/GW0056G4-SLV.html",
        "https://www.guess.com/us/en/men/accessories/sale/navy-and-rose-gold-tone-chronograph-watch-blue/U1254G3-BLUE.html",
        "https://www.guess.com/us/en/men/accessories/sale/silver-tone-chronograph-watch-silver/U0668G3-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/black-and-rose-gold-tone-watch-black/X90006G2S-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/blue-and-gold-tone-analog-watch-blue/Y36004G7-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/blue-and-rose-gold-tone-watch-blue/Y23006G7-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/brown-and-blue-chronograph-watch-brown/Y37002G7-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-2-tone-chronograph-watch-multiplecolors/Y81001G2MF-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-black-and-rose-gold-tone-chronograph-watch-multiplecolors/Y70002G2MF-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-black-and-rose-gold-tone-watch-rosegold/Y51002G2MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-blue-and-gold-tone-chronograph-watch-multiplecolors/Y70001G7MF-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-brown-and-silver-tone-chronograph-watch-nocolor/Y53004G1MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-gold-tone-and-black-chronograph-watch-nocolor/Y44006G2MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-gold-tone-and-black-leather-chronograph-watch.-nocolor/Y54007G2MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-navy-and-multi-tone-chronograph-watch-multiplecolors/Y53007G7MF-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-rose-gold-and-silver-tone-chronograph-watch-nocolor/Y23003G2MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-silver-tone-date-analog-watch-multiplecolors/Y61001G7MF-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-silver-tone-multifunction-watch-nocolor/Y44004G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/gc-sport-2-tone-chronograph-watch-multiplecolors/Y81002G5MF-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/multi-tone-chronograph-timepiece-nocolor/X72025G7S-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/multi-tone-chronograph-watch-silver/Y37003G7-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gc-swiss-timepieces/silver-tone-chronograph-watch-silver/Y08007G1-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-analog-watch-gold/GW0277G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-analog-watch-gold/GW0388G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-chronograph-watch-black/U1261G3-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-digital-chronograph-watch-multiplecolors/U0787G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-multifunction-watch-black/GW0205G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-multifunction-watch-black/GW0263G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-multifunction-watch-gold/GW0390G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-and-gold-tone-square-multifunction-watch-multiplecolors/GW0202G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/black-gold-tone-multifunction-watch-gold/GW0068G3-GLD.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/connoisseur-gold-tone-and-black-analog-watch-multiplecolors/GW0265G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/connoisseur-two-tone-analog-watch-multiplecolors/GW0265G5-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-analog-watch-multiplecolors/GW0265G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-gold/GW0330G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-multiplecolors/GW0200G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-chrono-look-watch-multiplecolors/GW0060G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-chronograph-watch-gold/U1314G1-GOLD.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-diamond-analog-watch-gold/U1315G2-GOLD.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-digital-watch-gold/GW0341G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-exposed-dial-multifunction-watch-gold/GW0325G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-multifunction-watch-gold/GW0264G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-multifunction-watch-gold/GW0334G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-multifunction-watch-gold/U1309G2-GOLD.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-multifunction-watch-nocolor/GW0278G2-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-silicone-digital-watch-multiplecolors/GW0272G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-tachymeter-watch-gold/GW0333G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-black-tachymeter-watch-multiplecolors/GW0204G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-champagne-chrono-look-watch-multiplecolors/GW0059G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-green-croc-watch-multiplecolors/GW0219G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-green-sport-watch-multiplecolors/GW0220G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-and-leather-multifunction-watch-multiplecolors/GW0262G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-barrel-analog-watch-gold/GW0387G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-chrono-look-multifunction-watch-gold/GW0068G2-GOLD.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-classic-multifunction-watch-gold/U0791G2-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-croc-strap-analog-watch-multiplecolors/GW0250G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-crystal-multifunction-watch-black/GW0048G2-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-digital-watch-gold/GW0271G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-exposed-dial-multifunction-watch-multiplecolors/GW0324G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-mesh-diamond-analog-watch-multiplecolors/GW0248G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-mesh-multifunctional-watch-gold/U1310G2-GOLD.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-multifunction-watch-multiplecolors/GW0094G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-multifunction-watch-multiplecolors/GW0209G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-multifunction-watch-multiplecolors/GW0260G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-rhinestone-multifunction-watch-gold/U1317G1-GOLD.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/gold-tone-rhinestone-multifunction-watch-multiplecolors/GW0261G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/oversized-gold-tone-multifunction-watch-multiplecolors/GW0208G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/paragon-gold-tone-and-green-analog-watch-multiplecolors/GW0213G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/perspective-gold-tone-and-black-analog-watch-multiplecolors/GW0276G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/two-tone-and-black-multifunction-watch-silver/U1107G6-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/western-analog-watch-multiplecolors/GW0295G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/gold-tone/white-and-gold-tone-digital-watch-multiplecolors/GW0225G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/black-and-tan-leather-chrono-look-watch-brown/GW0101G1-BROWN.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/black-diver-multifunction-watch-nocolor/GW0280G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/black-leather-analog-watch-black/GW0353G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/black-leather-strap-analog-watch-multiplecolors/GW0251G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/coffee-tone-and-brown-leather-multifunction-watch-multiplecolors/GW0331G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/coffee-tone-croc-strap-watch-multiplecolors/GW0204G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/gc-brown-and-silver-tone-chronograph-watch-nocolor/Y53004G1MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/gold-tone-and-black-leather-strap-analog-watch-multiplecolors/GW0251G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/rose-gold-tone-and-black-leather-chronographic-watch-black/GW0011G3-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/rose-gold-tone-and-leather-chrono-look-watch-multiplecolors/GW0067G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/leather/white-and-brown-daydate-watch-brown/GW0077G1-BROWN.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/black-diamond-analog-watch-black/U1315G3-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/black-logo-analog-watch-black/GW0266G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/blue-diamond-analog-watch-blue/U1315G4-BLUE.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/friendswithyou-petite-silicon-digital-watch-multiplecolors/V1057M2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/friendswithyou-rainbow-digital-watch-multiplecolors/V1059M2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/friendswithyou-silicon-digital-watch-multiplecolors/V1058M1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/guess-x-friendswithyou-petite-silicon-analog-watch-multiplecolors/V1057M2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/guess-x-friendswithyou-rainbow-digital-watch-multiplecolors/V1059M2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/guess-x-friendswithyou-silicone-digital-watch-multiplecolors/V1058M1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/neon-blue-oversized-digital-watch-blue/GW0050G1-BLUE.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/neon-green-oversized-digital-watch-green/GW0050G2-GRN.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/neon-orange-oversized-digital-watch-orange/GW0050G3-ORANG.html",
        "https://www.guess.com/us/en/men/accessories/watches/logo/turquoise-logo-analog-watch-turquoise/GW0266G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/blue-and-rose-gold-silicone-watch-multiplecolors/GW0057G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/blue-and-rose-gold-tone-digital-watch-multiplecolors/GW0225G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/blue-and-rose-gold-tone-silicone-watch-multiplecolors/GW0051G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/coffee-tone-and-leather-multifunction-watch-multiplecolors/GW0262G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/dos-rose-gold-tone-and-black-multifunction-watch-multiplecolors/GW0281G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/dos-rose-gold-tone-and-blue-dual-function-watch-multiplecolors/GW0281G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/gc-rose-gold-tone-chronographic-watch-nocolor/Y54002G2MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/navy-and-rose-gold-tone-multifunction-watch-blue/GW0263G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/paragon-rose-gold-tone-analog-watch-rosegold/GW0213G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-black-multifunction-watch-multiplecolors/GW0334G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-blue-analog-watch-multiplecolors/GW0251G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-blue-analog-watch-rosegold/GW0353G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-blue-multifunction-watch-multiplecolors/GW0206G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-blue-multifunction-watch-multiplecolors/GW0264G4-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-blue-multifunction-watch-rosegold/GW0326G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-brown-leather-watch-brown/GW0009G2-BROWN.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-brown-multiplecolors/GW0216G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-brown-watch-multiplecolors/GW0216G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-navy-analog-watch-rosegold/GW0250G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-navy-barrel-analog-watch-rosegold/GW0386G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-and-steel-chronographic-watch-nocolor/U1311G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/rose-gold-tone/rose-gold-tone-chrono-look-watch-pink/GW0068G6-ROGD.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/black-and-silver-tone-analog-watch-silver/GW0277G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/black-and-silver-tone-multifunction-watch-multiplecolors/GW0203G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/black-and-silver-tone-multifunction-watch-silver/GW0390G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/comet-silver-tone-analog-watch-multiplecolors/GW0221G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/comet-silver-tone-and-black-analog-watch-multiplecolors/GW0220G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/enterprise-silver-tone-and-brown-multifunction-watch-multiplecolors/GW0279G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/enterprise-silver-tone-multifunction-watch-multiplecolors/GW0279G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/gc-silver-tone-and-blue-chronograph-watch-multiplecolors/Y54003G7MF-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/gc-silver-tone-and-grey-watch-nocolor/Y53006G5MF-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/gc-silver-tone-date-analog-watch-multiplecolors/Y61001G7MF-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/gold-and-silver-tone-chrono-look-multifunction-watch-silver/GW0056G4-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/green-two-tone-diamond-analog-watch-silver/GW0010G2-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/green-two-tone-multifunction-watch-silver/GW0066G2-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/gunmetal-multifunction-watch-gray/GW0068G5-GUN.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/montre-analogique-argent%C3%A9e-et-noir-comet-multiplecolors/GW0220G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/multi-tone-and-blue-analog-watch-multiplecolors/GW0330G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/multi-tone-and-leather-multifunction-watch-multiplecolors/GW0262G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/oversized-silver-tone-multifunction-watch-multiplecolors/GW0208G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/paragon-silver-tone-and-blue-analog-watch-multiplecolors/GW0213G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/perspective-silver-tone-and-blue-analog-watch-multiplecolors/GW0276G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/polished-steel-analog-watch-silver/GW0069G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-analog-watch-grey/GW0265G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-analog-watch-silver/GW0330G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-analog-watch-silver/U1263G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-chrono-look-multifunction-watch-silver/GW0068G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-chrono-look-watch-multiplecolors/GW0053G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-croc-watch-multiplecolors/GW0219G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-dial-analog-watch-silver/U1172G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-digital-watch-silver/GW0341G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-leather-watch-black/GW0009G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-multifunction-watch-multiplecolors/GW0202G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-multifunction-watch-multiplecolors/GW0206G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-multifunction-watch-multiplecolors/GW0332G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-multifunction-watch-silver/GW0322G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-multifunction-watch-silver/GW0334G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-black-tachymeter-watch-silver/GW0333G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-blue-chrono-look-watch-silver/GW0056G2-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-blue-diamond-analog-watch-silver/GW0010G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-blue-multifunction-watch-silver/U1309G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-blue-sport-watch-multiplecolors/GW0220G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-blue-tachymeter-watch-multiplecolors/GW0329G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-brown-daydate-watch-silver/GW0076G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-denimanalog-watch-multiplecolors/GW0229G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-grey-diamond-analog-watch-silver/U1315G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-grey-mesh-multifunctional-watch-silver/U1310G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-and-navy-chronograph-watch-silver/U1104G3-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-barrel-analog-watch-silver/GW0387G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-croc-strap-analog-watch-multiplecolors/GW0250G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-exposed-dial-analog-watch-silver/GW0323G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-exposed-dial-multifunction-watch-silver/GW0324G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-mesh-diamond-analog-watch-multiplecolors/GW0248G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-multifunction-chrono-look-watch-silver/GW0056G1-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-multifunction-watch-multiplecolors/GW0094G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-multifunction-watch-multiplecolors/GW0209G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-multifunction-watch-multiplecolors/GW0215G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-multifunction-watch-multiplecolors/GW0260G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-multifunction-watch-nocolor/GW0278G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/silver-tone-rhinestone-multifunction-watch-multiplecolors/GW0261G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/transparent-and-silver-tone-multifunction-watch-multiplecolors/GW0203G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/two-tone-metal-and-green-dial-analog-watch-silver/U1172G5-SLV.html",
        "https://www.guess.com/us/en/men/accessories/watches/silver-tone/two-tone-silver-rose-gold-blue/GW0056G5-BLUE.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/44mm-black-leather-gc-smartwatch-strap-multiplecolors/TS3204G2-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/44mm-blue-perforated-guess-connect-smartwatch-strap-blue/CS1002S6-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/44mm-blue-textured-silicone-guess-connect-smartwatch-strap-blue/CS1002S14-BLUE.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/44mm-green-textured-silicone-guess-connect-smartwatch-strap-green/CS1002S15-GREEN.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/44mm-orange-textured-silicone-guess-connect-smartwatch-strap-orange/CS1002S16-ORANG.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/guess-connect-black-smartwatch--black/C1001G5-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/guess-connect-blue-and-rose-gold-tone-smartwatch-blue/C1002M2-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/smartwatch/olive-green-and-black-digital-watch-green/GW0342G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/beige-and-black-digital-watch-beige/GW0342G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-analog-watch-black/U1072G3-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-blue-digital-watch-black/C3001G3-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-gold-tone-analog-watch-black/U1161G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-gold-tone-analog-watch-black/U1264G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-gold-tone-multifunction-watch-black/GW0051G2-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-gold-tone-multifunction-watch-black/U1257G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-green-digital-watch-black/C3001G2-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-hematite-tone-analog-watch-black/U1161G2-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-red-digital-watch-black/C3001G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-red-multifunction-watch-multiplecolors/GW0325G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-red-silicone-multifunction-watch-red/GW0268G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-and-rose-gold-tone-watch-brown/U1058G2-BROWN.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-chrono-look-multifunction-watch-black/GW0264G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-multifunction-watch-black/GW0263G4-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-silicone-barrel-analog-watch-multiplecolors/GW0386G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-striped-multifunction-watch-black/GW0055G3-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-tone-and-black-dial-analog-watch-black/U1172G4-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-tone-and-black-leather-chronographic-watch-multiplecolors/GW0011G2-MUTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/black-triangle-logo-analog-watch-black/GW0337G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/blue-and-gold-tone-chronograph-watch-blue/U1049G2-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/blue-chrono-look-multifunction-watch-multiplecolors/GW0057G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/blue-two-tone-multifunction-watch-multiplecolors/GW0051G4-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/camo-chrono-look-multifunction-watch-green/GW0264G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/g-force-beige-digital-watch-multiplecolors/GW0269G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/g-force-black-digital-watch-black/GW0269G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/g-force-navy-digital-watch-multiplecolors/GW0269G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/g-force-red-digital-watch-multiplecolors/GW0269G5-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/gold-tone-and-black-chrono-look-multifunction-watch-black/GW0057G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/gold-tone-and-black-multifunction-watch-black/U1049G5-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/gold-tone-multifunction-watch-black/U1132G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/gunmetal-and-blue-analog-watch-gray/U1194G5-GUN.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/gunmetal-and-blue-mesh-multifunctional-watch-gray/U1310G3-GUN.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/iconic-red-sport-watch-red/U0979L3-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/iconic-white-sport-watch-white/U0979L1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/khaki-and-black-compass-analog-watch-multiplecolors/GW0328G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/navy-and-rose-gold-tone-chronograph-watch-blue/U1254G3-BLUE.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/olive-and-black-exposed-dial-multifunction-watch-green/GW0325G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/olive-and-black-multifunction-watch-green/GW0322G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/oversized-black-silicone-analog-and-digital-watch-black/U1299G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/oversized-red-silicone-analog-and-digital-watch-red/U1299G3-RED.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/oversized-white-silicone-analog-and-digital-watch-white/U1299G2-WHITE.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/red-and-black-multifunction-watch-red/U1049G6-RED.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/red-and-silver-tone-multifunction-watch-red/U1256G4-RED.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/red-multifunction-watch-red/GW0263G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/red-plastic-and-silicone-multifunction-watch-red/GW0203G5-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/rose-gold-tone-and-blue-silicone-multifunction-watch-blue/GW0203G7-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/rose-gold-tone-and-navy-silicone-multifunction-watch-blue/GW0268G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/silver-tone-and-white-silicone-multifunction-watch-white/GW0268G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/silver-tone-diamond-silicone-watch-black/U1221G1-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/sport-multifunction-watch-blue/U0799G6-BLUE.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/stealth-blue-digital-watch-multiplecolors/GW0270G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/stealth-clear-digital-watch-multiplecolors/GW0270G1-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/stealth-red-digital-watch-multiplecolors/GW0270G2-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/white-and-red-digital-watch-white/C3001G4-WHITE.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/yellow-and-turquoise-silicone-multifunction-watch-turquoise/GW0268G4-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/sport/yellow-plastic-and-silicone-multifunction-watch-yellow/GW0203G6-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/black-and-rose-gold-tone-multifunction-watch-black/U1055G3-BLK1.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/black-and-silver-tone-analog-watch-black/U1263G3-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/black-classic-style-watch-black/U0668G5-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/black-mesh-diamond-analog-watch-black/U0298G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/black-mesh-diamond-analog-watch-multiplecolors/GW0248G3-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/black-multifunction-watch-black/GW0068G4-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/black-polished-steel-analog-watch-black/GW0069G3-BLK.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/blue-and-rose-gold-tone-sport-watch-blue/U0366G4-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/blue-mesh-diamond-analog-watch-multiplecolors/GW0248G4-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/blue-round-diamond-mesh-watch-blue/U0297G2-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/connoisseur-black-analog-watch-multiplecolors/GW0265G4-MULTI.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/gold-tone-classic-dress-watch-gold/U0668G4-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/gold-tone-multifunction-watch--gold/U0799G2-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/multi-tone-sport-watch-brown/U0500G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/silver-tone-classic-watch-silver/U0668G7-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/silver-tone-multifunction-watch-silver/U0799G1-NC.html",
        "https://www.guess.com/us/en/men/accessories/watches/view-all/two-tone-chronograph-watch-silverrosegold/U1107G3-PNK.html",
        "https://www.guess.com/us/en/men/apparel/sale/view-all/black-and-gold-tone-multifunction-watch-black/GW0051G2-BLK.html",
        "https://www.guess.com/us/en/navy-and-gold-tone-chronograph-watch-gold/U1070L6-GOLD.html",
        "https://www.guess.com/us/en/navy-and-rose-gold-tone-analog-watch-blue/U1264G3-BLUE.html",
        "https://www.guess.com/us/en/originals/originals/capsules/bear-collection/guess-originals-blue-bear-analog-watch-blue/V1061M1-MULTI.html",
        "https://www.guess.com/us/en/originals/originals/capsules/bear-collection/guess-originals-denim-bear-analog-watch-multiplecolors/V1060M1-MULTI.html",
        "https://www.guess.com/us/en/originals/originals/friendswithyou-lookbook/friendswithyou-large-analog-silicon-watch-multiplecolors/V1056M1-MULTI.html",
        "https://www.guess.com/us/en/originals/originals/friendswithyou-lookbook/friendswithyou-large-logo-silicon-watch-multiplecolors/V1056M2-MULTI.html",
        "https://www.guess.com/us/en/originals/originals/friendswithyou-lookbook/friendswithyou-petite-analog-silicon-watch-multiplecolors/V1057M1-MULTI.html",
        "https://www.guess.com/us/en/originals/originals/friendswithyou-lookbook/guess-x-friendswithyou-large-analog-silicone-watch-multiplecolors/V1056M1-MULTI.html",
        "https://www.guess.com/us/en/originals/originals/friendswithyou-lookbook/guess-x-friendswithyou-large-logo-silicone-watch-multiplecolors/V1056M2-MULTI.html",
        "https://www.guess.com/us/en/originals/originals/friendswithyou-lookbook/guess-x-friendswithyou-petite-analog-silicone-watch-multiplecolors/V1057M1-MULTI.html",
        "https://www.guess.com/us/en/oversized-red-silicone-analog-and-digital-watch-red/U1299G3-RED.html",
        "https://www.guess.com/us/en/rhinestone-gold-tone-multifunction-watch-gold/U1156L2-GOLD.html",
        "https://www.guess.com/us/en/rhinestone-silver-tone-multifunction-watch-silver/U1156L1-SLV.html",
        "https://www.guess.com/us/en/rose-gold-tone-and-black-multifunction-watch-black/U1135L4-BLK.html",
        "https://www.guess.com/us/en/rose-gold-tone-and-black-multifunction-watch-blue/GW0030L5-BLUE.html",
        "https://www.guess.com/us/en/rose-gold-tone-and-blue-analog-watch-multiplecolors/GW0251G3-MULTI.html",
        "https://www.guess.com/us/en/rose-gold-tone-and-navy-silicone-multifunction-watch-blue/GW0268G3-MULTI.html",
        "https://www.guess.com/us/en/rose-gold-tone-diamond-mesh-watch-pink/U1197L6-ROGD.html",
        "https://www.guess.com/us/en/rose-gold-tone-logo-analog-watch-pink/U1142L4-ROGD.html",
        "https://www.guess.com/us/en/rose-gold-tone-multifunction-watch-pink/U1156L3-ROGD.html",
        "https://www.guess.com/us/en/rose-gold-tone-petite-crystal-watch-pink/U0135L3-NC.html",
        "https://www.guess.com/us/en/rose-gold-tone-square-multifunction-watch-nocolor/GW0104L3-NC.html",
        "https://www.guess.com/us/en/rose-gold-tone-watch-pink/U1070L3-NC.html",
        "https://www.guess.com/us/en/silver-tone-and-blue-chronograph-watch-silver/U1104G4-SLV.html",
        "https://www.guess.com/us/en/silver-tone-and-denimanalog-watch-multiplecolors/GW0228L1-MULTI.html",
        "https://www.guess.com/us/en/silver-tone-and-denimanalog-watch-multiplecolors/GW0229G1-MULTI.html",
        "https://www.guess.com/us/en/silver-tone-chronograph-watch-silver/U0668G3-NC.html",
        "https://www.guess.com/us/en/silver-tone-diamond-analog-watch-silver/U1194G1-SLV.html",
        "https://www.guess.com/us/en/silver-tone-diamond-analog-watch-silver/U1194G2-SLV.html",
        "https://www.guess.com/us/en/silver-tone-logo-analog-watch-silver/U1142L1-SLV.html",
        "https://www.guess.com/us/en/silver-tone-multifunction-watch-multiplecolors/GW0104L1-MULTI.html",
        "https://www.guess.com/us/en/silver-tone-multifunction-watch-silver/U1176G2-SLV.html",
        "https://www.guess.com/us/en/silver-tone-petite-crystal-watch-silver/U0135L1-NC.html",
        "https://www.guess.com/us/en/silver-tone-square-analog-watch-silver/GW0026L1-SLV.html",
        "https://www.guess.com/us/en/sport-two-tone-watch-gold/U1156L5-GOLD.html",
        "https://www.guess.com/us/en/stealth-blue-digital-watch-multiplecolors/GW0270G3-MULTI.html",
        "https://www.guess.com/us/en/stealth-clear-digital-watch-multiplecolors/GW0270G1-MULTI.html",
        "https://www.guess.com/us/en/stealth-red-digital-watch-multiplecolors/GW0270G2-MULTI.html",
        "https://www.guess.com/us/en/two-tone-petite-watch-silver/U0989L8-SLV.html",
        "https://www.guess.com/us/en/women/accessories/sale/gc-connect-rose-gold-tone-smartwatch-white/T33003L0-NC.html",
        "https://www.guess.com/us/en/women/accessories/view-all/guess-connect-white-and-rose-gold-tone-smartwatch-white/C1003L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/gold-tone-analog-watch-gold/U1117L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/gold-tone-analog-watch-gold/U1121L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/gold-tone-logo-analog-watch-gold/U1142L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/gold-tone-modern-woven-watch-gold/U0638L2-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/gold-tone-petite-watch-gold/U1209L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rhinestone-gold-tone-multifunction-watch-gold/U1156L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rhinestone-silver-tone-multifunction-watch-silver/U1156L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rose-gold-tone-diamond-mesh-watch-pink/U1197L6-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rose-gold-tone-logo-analog-watch-pink/U1142L4-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rose-gold-tone-mesh-strap-watch-rosegold/U1083L3-PNK.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rose-gold-tone-petite-diamond-analog-watch-pink/U1198L4-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rose-gold-tone-petite-watch-pink/U1209L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/rose-gold-tone-watch-pink/U1070L3-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/silver-and-gold-tone-crystal-accent-watch-silvergold/U0779L4-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/silver-tone-and-blue-logo-analog-watch-silver/U1083L4-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/silver-tone-and-pink-analog-watch-silver/U1062L2-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/silver-tone-logo-analog-watch-silver/U1142L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/silver-tone-rhinestone-analog-watch-silver/U1231L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/sport-two-tone-watch-gold/U1156L5-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/two-tone-petite-diamond-watch-silver/U1222L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/dressy/two-tone-petite-watch-silver/U0989L8-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces-/blue-and-rose-gold-tone-watch-rosegold/Y06009L7-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces-/gc-connect-multi-tone-smartwatch-rosegold/T33001L0-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces-/gc-white-and-gold-tone-watch-white/Y42001L1-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces-/rose-gold-tone-and-gray-watch-silverrosegold/Y16015L5-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces-/two-tone-multifunction-watch-silver/Y06010L1-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/cable-twist-petite-two-tone-watch-nocolor/Y39003L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-gold-tone-cable-twist-analog-watch-nocolor/Y56004L1MF-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-gold-tone-crystal-analog-watch-nocolor/Y64003L1MF-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-gold-tone-crystal-daydate-watch-multiplecolors/Y78002L1MF-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-rose-gold-tone-and-white-multifunction-watch-multiplecolors/Y65001L1MF-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-rose-gold-tone-cable-twist-analog-watch-blue/Y56002L1MF-TTIW.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-rose-gold-tone-cable-watch-multiplecolors/Y58001L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-silver-and-rose-gold-tone-multi-time-zone-watch-nocolor/Y16002L1MF-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-silver-and-rose-gold-tone-multi-time-zone-watch-nocolor/Y16015L5MF-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/gc-silver-tone-crystal-daydate-watch-multiplecolors/Y78003L1MF-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/rose-gold-tone-and-blue-cable-watch-nocolor/Y18005L7-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/rose-gold-tone-and-gray-watch-silverrosegold/Y16015L5-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/rose-gold-tone-and-white-timepiece-white/Y16004L1-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/silver-cable-timepiece-silver/Y16001L1-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/two-tone-multifunction-watch-multiplecolors/Y16002L1-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gc-swiss-timepieces/two-tone-multifunction-watch-silver/Y06010L1-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/2019-sparkling-pink-multifunction-watch-pink/U0032L9-PINK.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/blue-multifunction-watch-blue/GW0044L2-BLUE.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/blush-digital-watch-pink/GW0338L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/gc-silver-and-rose-gold-tone-watch-silver/Y48001L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/gc-white-and-rose-gold-tone-analog-watch-multiplecolors/Y46009L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/gold-tone-chain-analog-watch-gold/U1275L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/gold-tone-crystal-bangle-analog-watch-gold/U1288L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/gold-tone-sparkle-strap-watch-black/U1096L3-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/iridescent-rhinestone-multifunction-watch-purple/GW0104L4-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/rose-gold-tone-and-blue-silicone-multifunction-watch-rosegold/GW0257L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/rose-gold-tone-crystal-bangle-analog-watch-pink/U1288L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/rose-gold-tone-sparkle-strap-watch-black/U1096L5-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/silver-tone-chain-analog-watch-silver/U1275L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/silver-tone-crystal-bangle-analog-watch-silver/U1288L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/stainless-steel-and-gold-tone-multifunction-watch-black/U1291L1-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/stainless-steel-and-rose-gold-tone-multifunction-watch-blue/U1291L2-BLUE.html",
        "https://www.guess.com/us/en/women/accessories/watches/glitz/tie-dye-and-rhinestone-analog-watch-multiplecolors/GW0259L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/black-and-gold-tone-analog-watch-multiplecolors/GW0111L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/black-and-gold-tone-buckle-cuff-analog-watch-black/U1137L8-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/black-and-gold-tone-chronographic-watch-gold/GW0315L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/black-and-gold-tone-crystal-analog-watch-black/GW0252L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/black-and-gold-tone-digital-watch-multiplecolors/GW0224L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/black-and-gold-tone-multifunction-watch-multiplecolors/GW0118L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-analog-watch-gold/GW0028L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-analog-watch-gold/GW0308L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-analog-watch-gold/U1208L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-black/GW0034L1-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-gold/GW0307L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-gold/GW0312L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-gold/U0638L10-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-multiplecolors/GW0109L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-analog-watch-multiplecolors/GW0310L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-ceramic-multifunction-watch-multiplecolors/GW0273L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-chrono-look-watch-multiplecolors/GW0038L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-chronograph-watch-black/U1294L1-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-diamond-analog-watch-multiplecolors/GW0243L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-digital-multifunction-watch-gold/GW0339L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-multifunction-watch-multiplecolors/GW0030L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-multifunction-watch-multiplecolors/GW0105L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-black-shimmer-analog-watch-gold/GW0313L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-crystal-multifunction-watch-gold/GW0274L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-diamond-analog-watch-gold/GW0114L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-diamond-analog-watch-gold/GW0384L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-leather-chrono-look-watch-black/GW0036L2-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-pearl--analog-watch-pink/GW0381L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-red-analog-watch-multiplecolors/GW0034L6-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-red-multifunction-watch-red/GW0045L2-RED.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-rhinestone-analog-watch-gold/GW0286L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-rhinestone-analog-watch-multiplecolors/GW0249L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-rhinestone-multifunction-watch-gold/GW0320L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-and-white-diamond-analog-watch-gold/GW0003L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-champagne-analog-watch-gold/GW0033L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-chrono-look-crystal-watch-multiplecolors/GW0037L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-chrono-look-watch-gold/U1293L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-crystal-analog-watch-multiplecolors/GW0022L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-diamond-analog-watch-black/GW0004L1-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-diamond-analog-watch-gold/U1313L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-diamond-analog-watch-multiplecolors/GW0244L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-exposed-dial-analog-watch-multiplecolors/GW0302L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-glitter-analog-watch-gold/U1235L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-logo-analog-watch-multiplecolors/GW0292L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-logo-bangle-watch-multiplecolors/GW0112L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-mesh-analog-watch-gold/GW0354L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-mesh-and-crystal-analog-watch-gold/U1289L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-multifunction-watch-gold/GW0104L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-multifunction-watch-gold/GW0253L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-multifunction-watch-gold/GW0314L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-multifunction-watch-gold/U1070L2-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-ombre-crystal-analog-watch-gold/GW0020L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-quattro-g-analog-watch-gold/U1280L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-quattro-g-clear-analog-watch-gold/GW0300L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-rectangular-analog-watch-multiplecolors/GW0102L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-rhinestone-analog-watch-multiplecolors/GW0254L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-rhinestone-multifunction-watch-multiplecolors/GW0257L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-rose-analog-watch-multiplecolors/GW0242L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-square-analog-watch-gold/GW0026L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-square-analog-watch-multiplecolors/GW0294L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/gold-tone-square-multifunction-watch-gold/GW0309L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/mini-gold-tone-bracelet-watch-gold/U1134L6-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/pink-and-gold-tone-analog-watch-gold/GW0380L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/pink-and-rose-gold-tone-crystal-analog-watch-pink/GW0252L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/rainbow-rhinestone-multifunction-watch-multiplecolors/GW0258L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/rose-gold-tone-quattro-g-analog-watch-pink/U1280L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/sofia-gold-tone-crystal-analog-watch-multiplecolors/GW0288L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/gold-tone/two-tone-diamond-analog-watch-silver/GW0073L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/blue-logo-digital-watch-blue/C3002M5-BLUE.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/gold-tone-glitter-logo-watch-multiplecolors/GW0001L2-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/gold-tone-tiled-logo-analog-watch-gold/U1279L2-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/pink-logo-digital-watch-pink/C3002M4-PINK.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/red-logo-digital-watch-red/C3002M1-RED.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/rose-gold-tone-tiled-logo-analog-watch-pink/U1279L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/script-logo-analog-watch-multiplecolors/GW0293L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/silver-tone-glitter-logo-watch-multiplecolors/GW0001L1-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/silver-tone-tiled-logo-analog-watch-silver/U1279L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/logo/white-logo-digital-watch-white/C3002M3-WHITE.html",
        "https://www.guess.com/us/en/women/accessories/watches/petite/cable-twist-petite-two-tone-watch-nocolor/Y39003L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/petite/gold-tone-diamond-mesh-watch-gold/U1197L5-GOLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/petite/rose-gold-tone-petite-crystal-watch-pink/U0135L3-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/petite/rose-gold-tone-petite-mesh-watch-gold/U1009L3-ROGLD.html",
        "https://www.guess.com/us/en/women/accessories/watches/petite/silver-tone-analog-diamond-mesh-watch-silver/U1197L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/petite/silver-tone-and-blue-diamond-analog-watch-silver/U1197L2-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/petite/silver-tone-petite-crystal-watch-silver/U0135L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/crystal-rose-gold-tone-analog-watch-multiplecolors/GW0111L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/crystal-rose-gold-tone-multifunction-watch-multiplecolors/GW0118L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/floral-and-white-leather-analog-watch-multiplecolors/GW0240L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/floral-transparent-analog-watch-multiplecolors/GW0239L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/gc-black-and-rose-gold-tone-rhinestone-watch-multiplecolors/Y46005L2MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/gc-pink-and-rose-gold-tone-analog-watch-multiplecolors/Y46004L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/gc-rose-gold-tone-analog-watch-multiplecolors/Y48002L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/gc-rose-gold-tone-analog-watch-nocolor/Y46006L1MF-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/gc-rose-gold-tone-cable-watch-multiplecolors/Y58001L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/nude-and-rose-gold-tone-digital-watch-multiplecolors/GW0224L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/pink-and-rose-gold-tone-crystal-analog-watch-pink/GW0252L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/pink-rhinestone-analog-watch-pink/GW0032L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-analog-watch-multiplecolors/GW0028L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-analog-watch-pink/GW0033L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-analog-watch-rosegold/GW0307L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-analog-watch-rosegold/GW0308L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-analog-watch-rosegold/GW0312L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-black-multifunction-watch-black/U1094L6-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-black-multifunction-watch-multiplecolors/GW0113L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-blue-chronographic-watch-rosegold/GW0315L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-crystal-analog-watch-rosegold/GW0382L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-diamond-analog-watch-multiplecolors/GW0384L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-diamond-analog-watch-rosegold/GW0114L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-grey-analog-watch-pink/U0638L11-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-pearl-analog-watch-rosegold/GW0381L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-pink-chrono-look-watch-pink/GW0036L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-rhinestone-analog-watch-multiplecolors/GW0249L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-rhinestone-analog-watch-rosegold/GW0286L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-rhinestone-multifunction-watch-rosegold/GW0320L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-white-analog-watch-white/GW0034L2-WHITE.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-white-ceramic-multifunction-watch-multiplecolors/GW0273L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-white-chrono-look-watch-multiplecolors/GW0038L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-white-diamond-analog-watch-multiplecolors/GW0243L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-white-diamond-analog-watch-pink/GW0003L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-white-multifunction-watch-white/GW0030L3-WHITE.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-and-white-square-multifunction-watch-nocolor/GW0105L3-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-chrono-look-watch-pink/U1293L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-crystal-analog-watch-multiplecolors/GW0022L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-crystal-analog-watch-multiplecolors/GW0109L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-daydate-watch-pink/GW0047L2-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-diamond-analog-watch-multiplecolors/GW0244L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-diamond-analog-watch-pink/U1313L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-floral-crystal-analog-watch-multiplecolors/GW0242L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-glitter-logo-watch-rosegold/GW0001L3-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-heart-analog-watch-multiplecolors/GW0380L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-logo-analog-watch-pink/GW0027L2-PINK.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-logo-bangle-watch-multiplecolors/GW0112L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-mesh-analog-watch-rosegold/GW0354L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-mesh-and-crystal-analog-watch-pink/U1289L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-multifunction-watch-rosegold/GW0253L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-multifunction-watch-rosegold/GW0314L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-ombre-crystal-analog-watch-pink/GW0020L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-rectangular-analog-watch-multiplecolors/GW0102L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-rhinestone-analog-watch-multiplecolors/GW0254L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-rhinestone-multifunction-watch-multiplecolors/GW0257L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-square-analog-watch-multiplecolors/GW0026L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/rose-gold-tone-square-multifunction-watch-nocolor/GW0104L3-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/sofia-rose-gold-tone-watch-multiplecolors/GW0288L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/sofia-rose-gold-tone-watch-rosegold/GW0288L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/sparkling-pink-analog-watch-multiplecolors/GW0032L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/rose-gold-tone/two-tone-diamond-analog-watch-silver/GW0073L2-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/gc-silver-tone-analog-watch-multiplecolors/Y60002L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/gc-silver-tone-cable-watch-silver/Y58005L1MF-MUTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/iridescent-and-pastel-crystal-analog-watch-white/GW0017L1-WHITE.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/mini-silver-tone-and-blue-analog-watch-silver/U1134L5-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/mini-silver-tone-and-white-analog-watch-silver/U1134L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/model-analog-watch-multiplecolors/GW0289L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/pink-transparent-multifunction-sport-watch-multiplecolors/GW0041L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-analog-watch-multiplecolors/GW0028L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-analog-watch-multiplecolors/GW0033L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-analog-watch-multiplecolors/GW0111L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-analog-watch-silver/GW0298L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-analog-watch-silver/GW0308L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-black-diamond-analog-watch-silver/GW0003L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-blue-analog-watch-nocolor/GW0033L5-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-blue-analog-watch-silver/GW0307L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-blue-diamond-analog-watch-nocolor/GW0073L5-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-crystal-multifunction-watch-silver/GW0274L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-denim-logo-analog-watch-multiplecolors/GW0291L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-denimanalog-watch-multiplecolors/GW0228L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-diamond-analog-watch-silver/GW0114L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-diamond-analog-watch-silver/GW0384L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-pink-diamond-analog-watch-multiplecolors/GW0244L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-rhinestone-analog-watch-multiplecolors/GW0249L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-rhinestone-analog-watch-silver/GW0286L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-rhinestone-multifunction-watch-silver/GW0320L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-and-white-ceramic-multifunction-watch-multiplecolors/GW0273L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-chrono-look-watch-silver/U1293L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-crystal-analog-watch-multiplecolors/GW0022L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-crystal-chrono-look-watch-multiplecolors/GW0037L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-daydate-watch-silver/GW0047L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-diamond-analog-watch-silver/U1313L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-digital-watch-silver/GW0343L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-exposed-dial-analog-watch-silver/GW0302L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-glitter-analog-watch-silver/U1235L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-logo-analog-watch-multiplecolors/GW0292L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-logo-bangle-watch-multiplecolors/GW0112L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-mesh-analog-watch-silver/GW0354L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-mesh-and-crystal-analog-watch-silver/U1289L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-mother-of-pearl-multifunction-watch-silver/U1295L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-multifunction-watch-multiplecolors/GW0104L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-multifunction-watch-silver/GW0253L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-multifunction-watch-silver/GW0314L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-ombre-crystal-analog-watch-silver/GW0020L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-quattro-g-analog-watch-silver/U1280L1-SLV.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-rectangular-analog-watch-multiplecolors/GW0102L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-rhinestone-analog-watch-multiplecolors/GW0254L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-rose-crystal-analog-watch-multiplecolors/GW0242L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-square-analog-watch-multiplecolors/GW0294L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/silver-tone-square-multifunction-watch-silver/GW0309L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/sofia-silver-tone-watch-multiplecolors/GW0288L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/transparent-multifunction-sport-watch-multiplecolors/GW0041L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/two-tone-analog-watch-blue/GW0033L4-TTIW.html",
        "https://www.guess.com/us/en/women/accessories/watches/silver-tone/white-and-silver-tone-crystal-analog-watch-silver/GW0252L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/smartwatch/guess-connect-black-and-silver-tone-smartwatch-silver/C1003L3-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/smartwatch/guess-connect-blue-and-rose-gold-tone-smartwatch--rosegold/C1003L4-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/black-and-gold-tone-analog-watch-black/U1227L2-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/black-and-gold-tone-digital-watch-black/U1224L2-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/black-multifunction-watch-black/U1053L7-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/blue-multifunction-watch-blue/U1157L3-BLUE.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/blue-silicone-analog-watch-multiplecolors/GW0034L4-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/friendswithyou-yellow-digital-watch-multiplecolors/V1059M1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/gold-tone-and-black-multifunction-watch-black/U1160L1-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/guess-x-friendswithyou-yellow-digital-watch-multiplecolors/V1059M1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/iconic-black-sport-watch-black/U0979L2-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/navy-and-rose-gold-tone-analog-watch-blue/U1227L3-BLUE.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/pink-and-rose-gold-tone-digital-watch-pink/U0700L2-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/pink-silicone-chronograph-watch-multiplecolors/GW0255L3-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/tie-dye-silicone-chronograph-watch-multiplecolors/GW0030L6-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/turquoise-silicone-chronograph-watch-multiplecolors/GW0255L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/sport/white-silicone-chronograph-watch-multiplecolors/GW0255L1-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/unisex/guess-originals-black-logo-watch-black/V1003M1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/unisex/guess-originals-silver-tone-and-red-logo-watch-gold/V1003M3-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/unisex/tortoise-and-black-multifunction-watch-black/GW0306L2-MULTI.html",
        "https://www.guess.com/us/en/women/accessories/watches/unisex/two-tone-and-navy-multifunction-watch-pink/U1187L3-ROGD.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/blue-diamond-analog-watch-blue/GW0073L3-BLUE.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/gold-tone-and-blue-multifunction-watch-blue/U1053L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/gold-tone-and-brown-analog-watch-brown/U1230L2-BROWN.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/gold-tone-slim-classic-watch-gold/U0989L2-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/rose-gold-tone-and-black-multifunction-watch-black/U1135L4-BLK.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/rose-gold-tone-slim-classic-watch-gold/U0989L3-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/silver-tone-and-white-analog-watch-nocolor/U1059L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/silver-tone-slim-classic-watch-gold/U0989L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/silver-tone-watch-silver/U1070L1-NC.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/two-tone-and-red-multifunction-watch-red/U1157L2-RED.html",
        "https://www.guess.com/us/en/women/accessories/watches/view-all/two-tone-multifunction-watch-gold/U0799G4-NC.html",
        "https://www.guess.com/us/en/women/apparel/sale/view-all/gold-tone-mesh-analog-watch-gold/U1263G2-GOLD.html"
    ];
    for (const u of urls) {
        const ex = await extraction({ entry: u, });
        await channel.publish(
            'scraper',
            'scrape.data.raw',
            Buffer.from(JSON.stringify(ex)),
            { correlationId: shortid.generate() }
        );
        await new Promise(r => setTimeout(r, 5000));
    }
    console.log('done.....');
    process.exit(0);
})()